import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");


// 削除済み記事の 301 redirect（2026-05-09 品質監査により撤去 — _documents/_quality_audit/cross_site/2026-05-09_cross_site_report.md 参照）
// localePrefix: "as-needed" のため、ja は prefix なし、en は /en/ prefix
const REMOVED_ARTICLE_REDIRECTS_2026_05_09 = [
  { from: "/articles/gemini-api/premium-showcase-multimodal-app-development", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/google-document-ai-gemini-intelligent-document-processing-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/vertex-ai-search-gemini-enterprise-rag-production-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-cloud-run-usage-based-saas-complete-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-structured-output-advanced", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-live-api-realtime-voice-app-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-saas-monetization", to: "/articles/gemini-api" },
  { from: "/articles/gemini-dev/firebase-ai-logic-swiftui-ios-production-app-guide-2026", to: "/articles/gemini-dev" },
  // 2026-05-09 Tax content removal (backed up to _backup/tax_content_2026-05-09/, migrated to note.com)
  { from: "/blog/ai-tax-filing-and-fighting-injustice", to: "/blog" },
  { from: "/blog/gemini-workspace-long-battle-evidence-archive", to: "/blog" },
  { from: "/blog/gemini-workspace-tax-records-legal-documents", to: "/blog" },
  { from: "/blog/japan-tax-injustice-complete-record", to: "/blog" },
  { from: "/blog/tax-battle-complete-chronicle", to: "/blog" },
  { from: "/blog/toyama-darkness-uozu-tax-office-kura-ai-reform", to: "/blog" },
  { from: "/blog/toyama-tax-office-darkness-systemic-injustice", to: "/blog" },
  { from: "/blog/toyama-tax-office-kura-recording-refusal-health-crisis", to: "/blog" },
  { from: "/blog/uozu-tax-office-update-fighting-systemic-injustice", to: "/blog" },
  { from: "/blog/why-ai-should-replace-tax-officials", to: "/blog" },
  // ===== 品質整理 2026-05-15: 低品質記事削除（完全ガイド系/徹底解説系 183本）=====
  { from: "/articles/gemini-advanced/function-calling-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-imagen-3-image-generation-api-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-31-computer-use-complete-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/google-project-mariner-complete-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-gems-custom-instructions-click-conversion-optimization", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-lyria-3-pro-music-generation-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-chrome-auto-browse-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-computer-use-complete-setup-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-adaptive-thinking-auto-reasoning-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-3-deep-think-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-gems-custom-instructions-best-practices-complete-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/google-flow-veo3-ai-video-creation-guide-2026", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-advanced/gemini-api-advanced-multimodal-production-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-api/files-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-vercel-ai-sdk-nextjs-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-cloud-storage-integration", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-error-handling-retry-patterns", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-error-handling-troubleshooting", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-thinking-level-parameter-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/multimodal-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/thinking-level-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-realtime-translation-chat-app", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-flex-priority-inference-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-vuejs3-ai-chat-composables-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-notion-integration-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-multimodal-embedding-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-3-flash-agentic-vision-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/system-instructions-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-3-thinking-level-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-3-media-resolution-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-free-tier-complete-guide-2026", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-ios-shortcuts-automation-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-discord-bot-python-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-25-pro-generativelanguage-rest-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-builtin-tools-function-calling-combination", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/nano-banana-2-flash-image-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-interactions-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-tts-api-troubleshooting-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-streaming-function-calling", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/google-ai-studio-gemini-api-key-setup-and-management", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-multimodal-showcase", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-background-execution-async-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-youtube-video-summary-tool-python", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-url-context-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-practical-showcase", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-spend-caps-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-image-recognition-text-extraction-python", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-swift-ios-firebase-ai-logic-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-tts-api-text-to-speech-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-typescript-complete-beginners-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-31-pro-customtools-agent-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-python-automation-recipes", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/veo3-video-generation-api", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-nodejs-ai-microservice-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-hono-cloudflare-edge-ai-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-cloudflare-workers-edge-ai", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-cost-optimization", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/context-caching-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-live-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-25-flash-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-implicit-caching-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-response-language-fix", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-tts-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-embedding-2-multimodal-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-batch-api", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/file-api-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-openai-compatible-endpoint-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-workspace/gemini-custom-instructions-gems-best-practices-guide", to: "/articles/gemini-workspace" },
  { from: "/articles/gemini-basics/gemini-rsfc-structured-prompt-complete-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-troubleshooting-common-errors-2026", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-2-5-flash-complete-guide-2026", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-gems-custom-ai-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-chat-history-import-migration-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-31-pro-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-canvas-realtime-collaborative-editing", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-31-flash-lite-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/what-is-gemini", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-canvas-ai-mode-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-english-learning-ai-tutor-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-3-flash-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-31-flash-lite-workspace-ai-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-3-2-complete-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/notebooklm-gemini-ai-studio-combined-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-canvas-ai-mode-search-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/google-ai-pro-ultra-plan-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-import-chats-migration-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-ai-beginner-guide-2026", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-gems-custom-instructions-best-practices", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/google-stitch-vibe-design-voice-canvas-complete-guide-2026", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-3-pro-guide", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-basics/gemini-2-5-flash-vs-pro-when-to-use", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-dev/google-ai-studio-troubleshooting-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/nemoclaw-gemini-beginners-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-cli-plan-mode", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-flutter-firebase-ai-logic", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-code-assist-outline", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-3-2-duckdb-streamlit-data-agent-production-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-cli-march-2026-plan-mode-subagent-sandbox", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-api-bun-javascript-runtime-ai-backend-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/google-jules-tools-cli-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-code-assist-agent-mode", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-api-github-pr-code-review-bot", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-api-sveltekit-ai-chat-app-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-function-calling-complete-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/google-colab-mcp-server-ai-agent-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/google-adk-python-multi-agent-development-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-code-assist-agent-mode-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-code-assist-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/google-jules-coding-agent-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/project-idx-gemini-cloud-ide-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-updates/gemma-4-complete-guide", to: "/articles/gemini-updates" },
  { from: "/articles/gemini-updates/gemini-android-redesign-compact-overlay-floating-window", to: "/articles/gemini-updates" },
  { from: "/articles/gemini-updates/gemma-4-release-complete-guide", to: "/articles/gemini-updates" },
  { from: "/articles/gemini-updates/gemini-gmail-ai-overviews-inbox-2026", to: "/articles/gemini-updates" },
  { from: "/articles/gemini-updates/gemma-4-complete-guide-2026", to: "/articles/gemini-updates" },
  // 2026-05-15 Tax-related article removal (YMYL compliance for GSC崩壊 recovery)
  { from: "/articles/gemini-dev/gemini-2-5-pro-niche-vertical-saas-150k-monthly", to: "/articles/gemini-dev" },

  // 2026-05-15 GSC崩壊対応: TMPL_TITLE違反+他違反の記事を一括削除（Helpful Content System対応）
  { from: "/articles/gemini-advanced/gemini-2-5-pro-deep-research-guide", to: "/articles/gemini-advanced" },
  { from: "/articles/gemini-basics/what-is-gemma-4", to: "/articles/gemini-basics" },
  { from: "/articles/gemini-dev/gemini-code-assist-outline-feature-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/jules-ai-google-coding-agent-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-workspace/google-workspace-gemini-practical-daily-workflow", to: "/articles/gemini-workspace" },

  // 2026-05-15 GSC崩壊対応 Phase 3: 4+違反の重度低品質記事を削除
  { from: "/articles/gemini-api/gemini-api-embedding-errors-troubleshooting-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-pandas-data-analysis-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-php-laravel-ai-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-python-async-asyncio-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-api/gemini-api-redis-semantic-cache-guide", to: "/articles/gemini-api" },
  { from: "/articles/gemini-dev/gemini-api-react-ai-chat-ui-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-github-actions-ci-cd-guide", to: "/articles/gemini-dev" },
  { from: "/articles/gemini-dev/gemini-md-setup-guide", to: "/articles/gemini-dev" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-advanced/gemini-gems-paid-distribution-business-design-2026", to: "/articles/gemini-advanced" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-advanced/gemini-kindle-publishing-guide", to: "/articles/gemini-advanced" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-api/gemini-rag-query-decomposition-hyde-production-guide", to: "/articles/gemini-api" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-basics/gemini-gems-custom-business-tool-monetization", to: "/articles/gemini-basics" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-basics/gemini-google-tv-ai-integration-guide", to: "/articles/gemini-basics" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-basics/gemini-gems-monetization-guide", to: "/articles/gemini-basics" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-updates/weekly-pickup-2026-0417", to: "/articles/gemini-updates" },
  // 2026-05-25 YMYL (tax) removal
  { from: "/articles/gemini-updates/weekly-pickup-2026-0424", to: "/articles/gemini-updates" },
  // 2026-05-25 cross-site duplicate slug rename
  { from: "/articles/gemini-basics/ai-tools-directory-2026-part1", to: "/articles/gemini-basics/gemini-ai-tools-directory-2026-part1" },
  // 2026-05-25 cross-site duplicate slug rename
  { from: "/articles/gemini-basics/ai-tools-directory-2026-part2", to: "/articles/gemini-basics/gemini-ai-tools-directory-2026-part2" },
  // 2026-05-25 cross-site duplicate slug rename
  { from: "/articles/gemini-basics/ai-narration-video-workflow-2026", to: "/articles/gemini-basics/gemini-ai-narration-video-workflow-2026" },

  // === Merge consolidation (2026-06-09) — absorbed articles ===
{ from: "/articles/gemini-advanced/computer-use-guide", to: "/articles/gemini-advanced/gemini-computer-use-complete-guide" },
  { from: "/articles/gemini-advanced/gemini-computer-use-practical", to: "/articles/gemini-advanced/gemini-computer-use-complete-guide" },
  { from: "/articles/gemini-advanced/gemini-25-pro-thinking-budget-calibration-guide", to: "/articles/gemini-advanced/gemini-25-pro-thinking-budget-reasoning-control-guide" },
  { from: "/articles/gemini-advanced/gemini-gems-custom-instructions-best-practices", to: "/articles/gemini-advanced/gemini-gems-custom-instructions-best-practices-2026" },
  { from: "/articles/gemini-advanced/gemini-long-context-practical-reality", to: "/articles/gemini-advanced/gemini-long-context-practical-patterns" },
  { from: "/articles/gemini-advanced/gemini-multimodal-rag", to: "/articles/gemini-advanced/gemini-multimodal-rag-system" },
  { from: "/articles/gemini-advanced/gemini-vision-artwork-analysis-artist-perspective-review", to: "/articles/gemini-advanced/gemini-vision-artwork-analysis-artist-developer-review" },
  { from: "/articles/gemini-advanced/google-ai-ultra-deep-think-mariner-worth-it", to: "/articles/gemini-advanced/google-ai-ultra-deep-think-mariner-2026-guide" },
  { from: "/articles/gemini-api/gemini-2-5-pro-latest-api-implementation-guide-2026", to: "/articles/gemini-api/gemini-2-5-pro-latest-api-implementation-complete-guide" },
  { from: "/articles/gemini-api/gemini-api-multimodal-complete-guide", to: "/articles/gemini-api/gemini-2-multimodal-live-api-complete-guide" },
  { from: "/articles/gemini-api/gemini-25-pro-api-complete-guide-2026", to: "/articles/gemini-api/gemini-25-pro-api-troubleshooting-complete-guide" },
  { from: "/articles/gemini-api/gemini-25-pro-latest-api-production-guide", to: "/articles/gemini-api/gemini-25-pro-latest-api-practical-developer-guide" },
  { from: "/articles/gemini-api/gemini-25-pro-mastery-production-guide", to: "/articles/gemini-api/gemini-25-pro-production-complete-guide" },
  { from: "/articles/gemini-api/gemini-api-python-error-solutions", to: "/articles/gemini-api/gemini-api-authentication-error-solutions" },
  { from: "/articles/gemini-api/gemini-api-grounding-not-working-troubleshooting", to: "/articles/gemini-api/gemini-api-context-caching-not-working-troubleshooting" },
  { from: "/articles/gemini-api/gemini-api-error-fix-guide", to: "/articles/gemini-api/gemini-api-cors-error-browser-fix" },
  { from: "/articles/gemini-api/gemini-api-quota-429-error-troubleshooting", to: "/articles/gemini-api/gemini-api-error-troubleshooting-guide" },
  { from: "/articles/gemini-api/gemini-api-error-troubleshooting", to: "/articles/gemini-api/gemini-api-error-troubleshooting-guide" },
  { from: "/articles/gemini-api/gemini-api-streaming-function-calling-guide", to: "/articles/gemini-api/gemini-api-function-calling-complete-guide" },
  { from: "/articles/gemini-api/gemini-api-telegram-bot-python-guide", to: "/articles/gemini-api/gemini-api-line-bot-python-guide" },
  { from: "/articles/gemini-api/gemini-api-production-complete-guide", to: "/articles/gemini-api/gemini-api-swiftui-production-app-complete-guide" },
  { from: "/articles/gemini-api/gemini-api-production-error-handling-rate-limit-guide", to: "/articles/gemini-api/gemini-api-rate-limit-error-fix" },
  { from: "/articles/gemini-api/gemini-api-rate-limiting-quota-management", to: "/articles/gemini-api/gemini-api-rate-limiting-quota-management-production-guide" },
  { from: "/articles/gemini-api/gemini-api-request-hedging-tail-latency-production-design", to: "/articles/gemini-api/gemini-api-request-hedging-p99-latency-design" },
  { from: "/articles/gemini-api/gemini-api-slack-bot-guide", to: "/articles/gemini-api/gemini-api-slack-bot-production-guide" },
  { from: "/articles/gemini-api/gemini-api-slow-response-timeout-fix", to: "/articles/gemini-api/gemini-api-slow-response-timeout-diagnosis" },
  { from: "/articles/gemini-api/gemini-api-structured-output-schema-versioning-evolution", to: "/articles/gemini-api/gemini-api-structured-output-schema-evolution-production-design" },
  { from: "/articles/gemini-api/gemini-file-search-api-guide", to: "/articles/gemini-api/gemini-file-search-api-grounding-guide" },
  { from: "/articles/gemini-api/gemini-function-calling-production-guide", to: "/articles/gemini-api/gemini-function-calling-guide" },
  { from: "/articles/gemini-api/gemini-function-calling-practical-guide", to: "/articles/gemini-api/gemini-function-calling-guide" },
  { from: "/articles/gemini-api/gemini-function-calling-production", to: "/articles/gemini-api/gemini-function-calling-guide" },
  { from: "/articles/gemini-basics/gemini-ai-tools-directory-2026-part1", to: "/articles/gemini-basics/gemini-ai-tools-directory-2026-part2" },
  { from: "/articles/gemini-basics/gemini-gems-custom-instructions-complete-guide", to: "/articles/gemini-basics/gemini-gems-custom-instructions-complete-guide-2026" },
  { from: "/articles/gemini-basics/gemini-gems-custom-instructions-troubleshooting", to: "/articles/gemini-basics/gemini-gems-custom-instructions-mastery" },
  { from: "/articles/gemini-basics/gemini-gems-custom-instructions-not-working", to: "/articles/gemini-basics/gemini-gems-custom-instructions-mastery" },
  { from: "/articles/gemini-dev/gemini-api-django-ai-web-app-guide", to: "/articles/gemini-dev/gemini-api-gradio-ai-web-app-tutorial" },
  { from: "/articles/gemini-dev/gemini-api-electron-desktop-app-complete-guide", to: "/articles/gemini-dev/gemini-api-tauri-desktop-ai-app-complete-guide" },
  { from: "/articles/gemini-dev/gemini-api-nuxt3-fullstack-ai-production-guide", to: "/articles/gemini-dev/gemini-api-supabase-fullstack-ai-app-production-guide" },
  { from: "/articles/gemini-dev/gemini-code-assist-agent-mode-not-working-fix-2026", to: "/articles/gemini-dev/gemini-code-assist-not-working-fix" },
  { from: "/articles/gemini-dev/gemini-code-assist-outline-development-guide", to: "/articles/gemini-dev/gemini-code-assist-outline-practical-guide" },
  { from: "/articles/gemini-dev/gemini-code-assist-outline-guide", to: "/articles/gemini-dev/gemini-code-assist-outline-practical-guide" },
  { from: "/articles/gemini-dev/gemini-code-assist-outline-feature", to: "/articles/gemini-dev/gemini-code-assist-outline-practical-guide" },
  { from: "/articles/gemini-dev/google-ai-studio-fullstack-vibe-coding", to: "/articles/gemini-dev/gemini-vibe-coding-ai-studio-practical" },
  { from: "/articles/gemini-dev/google-ai-studio-build-mode-practical-guide", to: "/articles/gemini-dev/google-ai-studio-build-mode-errors-troubleshooting" },
  { from: "/articles/gemini-dev/vertex-ai-quickstart", to: "/articles/gemini-dev/vertex-ai-gemini-production" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0512", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0519", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0515", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0526", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0522", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0501", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0428", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0529", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0414", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0403", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0421", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0331", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0505", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0602", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0410", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0325", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-updates/weekly-pickup-2026-0327", to: "/articles/gemini-updates/weekly-pickup-2026-0508" },
  { from: "/articles/gemini-workspace/gemini-workspace-integration-troubleshooting-faq", to: "/articles/gemini-workspace/gemini-workspace-integration-troubleshooting" },
];

const buildAuditRedirects = () => {
  const out: { source: string; destination: string; permanent: true }[] = [];
  for (const { from, to } of REMOVED_ARTICLE_REDIRECTS_2026_05_09) {
    out.push({ source: from, destination: to, permanent: true });
    out.push({ source: `/en${from}`, destination: `/en${to}`, permanent: true });
  }
  return out;
};

const nextConfig: NextConfig = {
  compress: true,
  poweredByHeader: false,
  async redirects() {
    return [
      ...buildAuditRedirects(),
      // Legacy/orphan URL surfaced in GSC (2026-04-25): non-existent article slug, redirect to closest match
      {
        source: "/articles/gemini-api/gemini-api-multimodal-guide",
        destination: "/articles/gemini-api/multimodal-api-guide",
        permanent: true,
      },
      {
        source: "/:locale(ja|en)/articles/gemini-api/gemini-api-multimodal-guide",
        destination: "/:locale/articles/gemini-api/multimodal-api-guide",
        permanent: true,
      },
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
        ],
      },
      {
        source: "/(.*)\\.(js|css|woff2|woff|ttf|ico|png|jpg|jpeg|svg|webp)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
    ];
  },
};

export default withNextIntl(nextConfig);
